#ifndef ENCODER_INPUT_H
#define ENCODER_INPUT_H

/*
ROBOT ORIENTATION
         FRONT
    MOTOR1  MOTOR3  
    MOTOR2  MOTOR4  (4WD/DIFFERENTIAL)
         BACK
*/

// INVERT ENCODER DIRECTIONS
#define ENCODER1_INV true
#define ENCODER2_INV true
#define ENCODER3_INV false 
#define ENCODER4_INV false

// #define ENCODER1_INCRIMENT 32
#define ENCODER1_PIN_A 25
#define ENCODER1_PIN_B 26

// #define ENCODER2_INCRIMENT 19
#define ENCODER2_PIN_A 14  
#define ENCODER2_PIN_B 12
  
// #define ENCODER3_INCRIMENT 26
#define ENCODER3_PIN_A 19
#define ENCODER3_PIN_B 18

// #define ENCODER4_INCRIMENT 17
#define ENCODER4_PIN_A 15 
#define ENCODER4_PIN_B 13

#define ENCODER1_PULSES_PER_REVOLUTION 2500
#define ENCODER2_PULSES_PER_REVOLUTION 2000
#define ENCODER3_PULSES_PER_REVOLUTION 2500
#define ENCODER4_PULSES_PER_REVOLUTION 2500

#endif