#ifndef ENCODER_INPUT_H
#define ENCODER_INPUT_H

/*
ROBOT ORIENTATION
         FRONT
    MOTOR1  MOTOR2  (2WD/ACKERMANN)
    MOTOR3  MOTOR4  (4WD/MECANUM)
         BACK
*/

// INVERT ENCODER DIRECTIONS
#define ENCODER1_INV true
#define ENCODER2_INV false
#define ENCODER3_INV true 
#define ENCODER4_INV false

#define ENCODER1_INCRIMENT 32
#define ENCODER1_PIN_A 33
#define ENCODER1_PIN_B 25

#define ENCODER2_INCRIMENT 19
#define ENCODER2_PIN_A 18  
#define ENCODER2_PIN_B 5
  
#define ENCODER3_INCRIMENT 26
#define ENCODER3_PIN_A 27
#define ENCODER3_PIN_B 14

#define ENCODER4_INCRIMENT 17
#define ENCODER4_PIN_A 16 
#define ENCODER4_PIN_B 4

#define ENCODER1_PULSES_PER_REVOLUTION 2500
#define ENCODER2_PULSES_PER_REVOLUTION 2000
#define ENCODER3_PULSES_PER_REVOLUTION 2500
#define ENCODER4_PULSES_PER_REVOLUTION 2500

#endif